#!/bin/bash

userkey() {
    cat $HOME/.cache/eww/weather-credentials/key
}

cityid() {
    cat $HOME/.cache/eww/weather-credentials/city
}

if [[ "$1" == "-key" ]]; then
    userkey
elif [[ "$1" == "-id" ]]; then
    cityid
fi
