#!/bin/bash

cpu() {
    mpstat | awk {'print $4'} | sed -n '4p'
}

memory() {
    printf "%.2f\n" $(free -m | grep Mem | awk '{print ($3/$2)*100}')
}

disk() {
    df -h / | awk '{print $5}' | tail -n 1 | sed 's/%//g'
}

battery() {
    bat=$(ls /sys/class/power_supply | grep BAT | head -n 1)
    if [[ $bat ]]; then
      percentage=$(cat /sys/class/power_supply/$bat/capacity)
      if [ $percentage -le 5 ]; then
        icon=""
        echo "${icon}  ${percentage}%"
      fi
      if [ $percentage -gt 5 ] && [ $percentage -le 45 ]; then
        icon=""
        echo "${icon}  ${percentage}%"
      fi
      if [ $percentage -gt 45 ] && [ $percentage -le 65 ]; then
        icon=""
        echo "${icon}  ${percentage}%"
      fi
      if [ $percentage -gt 65 ] && [ $percentage -le 85 ]; then
        icon=""
        echo "${icon}  ${percentage}%"
      fi
      if [ $percentage -gt 85 ] && [ $percentage -le 100 ]; then
        icon=""
        echo "${icon}  ${percentage}%"
      fi
    fi
}

brightness() {
    if [[ $(ls /sys/class/backlight | head -n 1) ]]; then
        light -G
    fi
}

if [[ "$1" == "-c" || "$1" == "--cpu" ]]; then
    cpu
elif [[ "$1" == "-m" || "$1" == "--memory" ]]; then
    memory
elif [[ "$1" == "-c" || "$1" == "--cpu" ]]; then
    cpu
elif [[ "$1" == "-d" || "$1" == "--disk" ]]; then
    disk
elif [[ "$1" == "-b" || "$1" == "--battery" ]]; then
    battery
elif [[ "$1" == "-l" || "$1" == "--brightness" ]]; then
    brightness
fi
